In [3]:
##Natural langauge processing
##NLTK
#TOKENIZATION
paragraph = """I have three visions for India. In 3000 years of our history, people from all over
               the world have come and invaded us, captured our lands, conquered our minds.
               From Alexander onwards, the Greeks, the Turks, the Moguls, the Portuguese, the British,
               the French, the Dutch, all of them came and looted us, took over what was ours.
               Yet we have not done this to any other nation. We have not conquered anyone.
               We have not grabbed their land, their culture,
               their history and tried to enforce our way of life on them.
               Why? Because we respect the freedom of others.That is why my
               first vision is that of freedom. I believe that India got its first vision of
               this in 1857, when we started the War of Independence. It is this freedom that
               we must protect and nurture and build on. If we are not free, no one will respect us.
               My second vision for India’s development. For fifty years we have been a developing nation.
               It is time we see ourselves as a developed nation. We are among the top 5 nations of the world
               in terms of GDP. We have a 10 percent growth rate in most areas. Our poverty levels are falling.
               Our achievements are being globally recognised today. Yet we lack the self-confidence to
               see ourselves as a developed nation, self-reliant and self-assured. Isn’t this incorrect?
               I have a third vision. India must stand up to the world. Because I believe that unless India
               stands up to the world, no one will respect us. Only strength respects strength. We must be
               strong not only as a military power but also as an economic power. Both must go hand-in-hand.
               My good fortune was to have worked with three great minds. Dr. Vikram Sarabhai of the Dept. of
               space, Professor Satish Dhawan, who succeeded him and Dr. Brahm Prakash, father of nuclear material.
               I was lucky to have worked with all three of them closely and consider this the great opportunity of my life.
               I see four milestones in my career"""

import nltk
from nltk.corpus import stopwords
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')
sen = nltk.sent_tokenize(paragraph)
words = nltk.word_tokenize(paragraph)

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...


In [ ]:
##stemming and lemmatization
from nltk.stem import PorterStemmer
from nltk.stem import WordNetLemmatizer
import re

In [ ]:
pr = PorterStemmer()

for i in range(len(sen)):
  para = re.sub('[^a-zA-Z]',' ', sen[i])
  para = para.lower()
  para = para.split()

  para = [pr.stem(word) for word in para if word not in set(stopwords.words('english'))]

  sen[i] = ' '.join(para)

sen[1]


'year histori peopl world come invad us captur land conquer mind'

In [ ]:
le = WordNetLemmatizer()
for i in range(len(sen)):
  para = re.sub('[^a-zA-Z]',' ', sen[i])
  para = para.lower()
  para = para.split()

  para = [le.lemmatize(word) for word in para if word not in set(stopwords.words('english'))]

  sen[i] = ' '.join(para)

sen[1]

'year histori peopl world come invad u captur land conquer mind'

In [ ]:
##after finding root words which are only usefull to analyse
##convert words to vectors . feature representation
##bag of words , TF-IDF
#1) bag of words - histogram, and  sort and apply BOW
#dis . adv. = semantic meaning not present
#2) TF-IDF - tf = no. of occ. of a word / no. of words in a sent
#idf = log(no. of sent / no. of sent cont that word )
#tf * idf = final vector repre.



In [ ]:
#spam classifier
import pandas as pd
new = []
data = pd.read_csv('SMSSpamCollection.csv', sep = '\t',names = ['labels','messages'])
data.head()
#test preprocessing
for i in range(len(data['messages'])):
  msg = re.sub('[^a-zA-Z]', ' ', data['messages'][i])
  msg = msg.lower()
  msg = msg.split()
  msg = [le.lemmatize(word) for word in msg if word not in stopwords.words('english')]
  msg = ' '.join(msg)
  new.append(msg)

new[1]

'ok lar joking wif u oni'

In [ ]:
#using BOW or tf-idf
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import CountVectorizer

tf = TfidfVectorizer()

fin = tf.fit_transform(new).toarray()
fin.shape


(5572, 7098)

In [ ]:
fin

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [ ]:
data['labels'] = data['labels'].map({'ham':1 , 'spam':0})


from sklearn.model_selection import train_test_split


In [ ]:
Y= pd.DataFrame(data['labels'])
X =pd.DataFrame(fin)

In [ ]:
from nltk.classify.maxent import train_maxent_classifier_with_gis
x_train,x_test,y_train,y_test = train_test_split(X,Y,test_size = 0.3,random_state = 0)

In [ ]:
#naive bayes theorem
#mulinomialNB GaussianNB
from sklearn.naive_bayes import MultinomialNB
mb =MultinomialNB()
model = mb.fit(X,Y)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [ ]:
y_pred = model.predict(x_test)


In [ ]:
from sklearn.metrics import accuracy_score
ac = accuracy_score(y_test,y_pred)
ac

0.9826555023923444

In [ ]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)
cm

array([[ 192,   29],
       [   0, 1451]])

In [ ]:
#spam classifier


In [1]:
# IMDB project using embedding layer ,one-hot OR tokenize .
#IMDB with WORD2VEC from scratch using GENSIM and BI-LSTM
#pre trained word emb. like owrd2vec or glove


In [1]:
#read the data
import pandas as pd
from google.colab import drive
drive.mount('/content/drive')

dataset = pd.read_csv("/content/drive/My Drive/Colab Notebooks/NLP datasetIMDB Dataset.csv")
# dataset = pd.read_csv('heart1.csv')
dataset

Mounted at /content/drive


review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. <br /><br />The...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[50000 rows x 2 columns]

In [2]:
#slicing for first 5000 rows
data = dataset.iloc[0:10000,:]

In [4]:
data.isnull().sum()
data.duplicated().sum()
#drop  duplicates
data.drop_duplicates(inplace =True)

<ipython-input-4-df3e0635f7b8>:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.drop_duplicates(inplace =True)


In [3]:
data.shape

(10000, 2)

In [3]:
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')
nltk.download('punkt')
nltk.download('wordnet')
import gensim.downloader as api
glove_gensim  = api.load('glove-wiki-gigaword-100')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...


[==============================================----] 93.0% 119.2/128.1MB downloaded


In [4]:
data['review'][5]

'Probably my all-time favorite movie, a story of selflessness, sacrifice and dedication to a noble cause, but it\'s not preachy or boring. It just never gets old, despite my having seen it some 15 or more times in the last 25 years. Paul Lukas\' performance brings tears to my eyes, and Bette Davis, in one of her very few truly sympathetic roles, is a delight. The kids are, as grandma says, more like "dressed-up midgets" than children, but that only makes them more fun to watch. And the mother\'s slow awakening to what\'s happening in the world and under her own roof is believable and startling. If I had a dozen thumbs, they\'d all be "up" for this movie.'

In [5]:
##text pre processing

#stemming ,lemmaztizing , remove stop words,lower sent . will go with stemming since lemmatizing takes time and problem stmt doesnt need
import re
from nltk.stem import WordNetLemmatizer
ps = WordNetLemmatizer()
corpus =[]
for i in range(len(data['review'])):
  review = re.sub('[^a-zA-Z]',' ', data['review'][i])
  review = review.lower()
  review = nltk.word_tokenize(review)
  review = [ps.lemmatize(word) for word in review if word not in stopwords.words('english')]
  review = ' '.join(review)
  corpus.append(review)

corpus[5]


'probably time favorite movie story selflessness sacrifice dedication noble cause preachy boring never get old despite seen time last year paul lukas performance brings tear eye bette davis one truly sympathetic role delight kid grandma say like dressed midget child make fun watch mother slow awakening happening world roof believable startling dozen thumb movie'

In [ ]:
#TF-IDF vectorization
##after finding root words which are only usefull to analyse
##convert words to vectors . feature representation
##bag of words , TF-IDF
#1) bag of words - histogram, and  sort and apply BOW- takes frequency of word and vectored
#dis . adv. = semantic meaning not present
#2) TF-IDF - tf = no. of occ. of a word / no. of words in a sent
#idf = log(no. of sent / no. of sent cont that word )
#tf * idf = final vector repre.


#from sklearn.feature_extraction.text import TfidfVectorizer
#tv = TfidfVectorizer(max_features = 27000)
#vec = tv.fit_transform(corpus).toarray()
#vec


array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [6]:
#tokenize sentences or we can use one hot encoding . since tokenizer preserves semtantic maeaning as it was labeled in seuqnece order
from tensorflow.keras.preprocessing.text import Tokenizer

tok = Tokenizer()
tok.fit_on_texts(corpus)
token = tok.texts_to_sequences(corpus)
token[4]


[28369,
 6066,
 34,
 6,
 179,
 1977,
 1277,
 3,
 33,
 264,
 6066,
 645,
 72,
 4244,
 2772,
 234,
 2188,
 2,
 102,
 782,
 72,
 179,
 380,
 811,
 22,
 189,
 412,
 1353,
 1,
 1,
 5235,
 2259,
 22225,
 71,
 415,
 56,
 3929,
 99,
 694,
 6,
 76,
 714,
 189,
 8,
 348,
 3650,
 4,
 2968,
 4,
 25,
 78,
 271,
 252,
 4,
 102,
 32,
 890,
 82,
 1934,
 12103,
 3,
 3386,
 16439,
 44,
 525,
 14,
 22,
 336,
 86,
 336,
 12104,
 1,
 1,
 27,
 4,
 11,
 844,
 245,
 189,
 638,
 4886,
 4,
 8785,
 93,
 377,
 514,
 46,
 145,
 234,
 2188,
 63,
 3718,
 9297,
 4,
 28370,
 276,
 22,
 1353,
 1,
 1,
 45,
 7,
 264,
 6066,
 305,
 1024,
 8303,
 4143,
 3387,
 2815,
 2479,
 373,
 14700,
 6067,
 16440,
 258,
 872,
 92,
 13,
 8,
 49,
 912,
 1,
 1,
 509,
 264,
 6066,
 7,
 1878,
 11199,
 14701,
 271,
 54]

In [8]:
tok.word_index['gypo']

4607

In [9]:
#creating wword2vec
word=[]
import gensim
#simple preprocess
from gensim.utils import simple_preprocess
for sent in corpus:
  sent_tok =sent_tokenize(sent)

  word.append(sent_tok)

#import gensim
#mod = gensim.models.Word2Vec(min_count = 2,window = 10,workers = 4,sg = 0)

NameError: ignored

AttributeError: ignored

In [7]:
import gensim
word=[]
from nltk import sent_tokenize
#simple preprocess
from gensim.utils import simple_preprocess
for sent in corpus:
  sent_tok =sent_tokenize(sent)
  for sen in sent_tok:
    word.append(simple_preprocess(sen))


word[4]

['petter',
 'mattei',
 'love',
 'time',
 'money',
 'visually',
 'stunning',
 'film',
 'watch',
 'mr',
 'mattei',
 'offer',
 'vivid',
 'portrait',
 'human',
 'relation',
 'movie',
 'seems',
 'telling',
 'money',
 'power',
 'success',
 'people',
 'different',
 'situation',
 'encounter',
 'br',
 'br',
 'variation',
 'arthur',
 'schnitzler',
 'play',
 'theme',
 'director',
 'transfer',
 'action',
 'present',
 'time',
 'new',
 'york',
 'different',
 'character',
 'meet',
 'connect',
 'one',
 'connected',
 'one',
 'way',
 'another',
 'next',
 'person',
 'one',
 'seems',
 'know',
 'previous',
 'point',
 'contact',
 'stylishly',
 'film',
 'sophisticated',
 'luxurious',
 'look',
 'taken',
 'see',
 'people',
 'live',
 'world',
 'live',
 'habitat',
 'br',
 'br',
 'thing',
 'one',
 'get',
 'soul',
 'picture',
 'different',
 'stage',
 'loneliness',
 'one',
 'inhabits',
 'big',
 'city',
 'exactly',
 'best',
 'place',
 'human',
 'relation',
 'find',
 'sincere',
 'fulfillment',
 'one',
 'discerns',
 '

In [8]:
vector_size = 100
vocab_size = len(tok.word_index)+1
vocab_size
import numpy as np
gensim_weight_matrix = np.zeros((vocab_size ,vector_size))
gensim_weight_matrix.shape
for word, index in tok.word_index.items():
  try:
    embedding_vector = glove_gensim[word]
    if embedding_vector is not None:

      gensim_weight_matrix[index] = embedding_vector
  except:
    pass
    #gensim_weight_matrix[index] = np.zeros(100)

In [9]:
#glove_gensim.wv.vocab

In [34]:
#words =[]
#from gensim.utils import simple_preprocess
#from nltk import sent_tokenize
#for sent in corpus:
#  sent_tok= sent_tokenize(sent)
#  for sent in sent_tok:
#    words.append(simple_preprocess(sent))






In [10]:
#word2vec from scratch
model = gensim.models.Word2Vec(word,min_count =2,vector_size = 100,window =10)

In [13]:
model.wv.most_similar('good')

[('nice', 0.7132898569107056),
 ('decent', 0.7026219964027405),
 ('alittl', 0.6788695454597473),
 ('cool', 0.6782465577125549),
 ('great', 0.6735098958015442),
 ('rest', 0.6635268926620483),
 ('gackt', 0.6625411510467529),
 ('awesom', 0.6567946672439575),
 ('bad', 0.6563290953636169),
 ('ok', 0.6514793038368225)]

In [12]:
model.wv['luck']

array([-0.16923144,  0.13645564,  0.17460713,  0.2896986 , -0.37192786,
       -0.3550583 ,  0.28036726,  0.5245499 , -0.17173856, -0.20589738,
        0.0433338 , -0.3682327 , -0.0676634 , -0.08790237,  0.09485745,
       -0.1265011 ,  0.04680638, -0.15590988, -0.10902848, -0.47187313,
        0.01359815,  0.21750419,  0.45325395, -0.23829065,  0.20009011,
        0.04160297, -0.54507273, -0.03894999, -0.24580392,  0.3396509 ,
        0.18229653,  0.07586828,  0.41865104, -0.32435107, -0.18228619,
        0.18466097, -0.02009765, -0.25769556, -0.11910836, -0.5273382 ,
        0.10548978, -0.00331024, -0.02145283, -0.03142975,  0.3290306 ,
       -0.2533805 , -0.04199367, -0.27876532,  0.06735132,  0.18512565,
       -0.17947811, -0.2116105 , -0.06015578, -0.13917303, -0.0692429 ,
        0.15382439,  0.24260534, -0.17129382, -0.18907833,  0.29765126,
       -0.13435751,  0.04404669, -0.05857117,  0.1828133 , -0.11528531,
        0.34956756,  0.01909676,  0.5154034 , -0.4878539 ,  0.14

In [10]:
#padding
from tensorflow.keras.preprocessing.sequence import pad_sequences

padded = pad_sequences(token,maxlen = 955,padding = 'post' )

In [15]:
#tok.word_index.items()
len(model.wv)

21974

In [18]:
#create embedding matrix
import numpy as np
embedding_matrix = np.zeros((vocab_size,100))
for word,i in tok.word_index.items():
  if word in model.wv:
    embedding_matrix[i] = model.wv[word]

embedding_matrix



array([[ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.64383554, -0.03695136,  1.40076602, ...,  0.74915904,
         1.21237123,  0.58420777],
       [ 0.4101513 ,  0.45986262,  0.87955761, ...,  0.63822699,
        -1.16521251,  0.48246714],
       ...,
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ]])

In [19]:
embedding_matrix.shape

(34953, 100)

In [11]:
#embedding layer
from tensorflow.keras.layers import Embedding,Bidirectional,LSTM,Dense
from tensorflow.keras.models import Sequential
model = Sequential()
model.add(Embedding(vocab_size,100,weights = [gensim_weight_matrix],input_length= 955))
model.add(Bidirectional(LSTM(64)))
model.add(Dense(32,activation = 'relu'))
model.add(Dense(1,activation='sigmoid'))

In [12]:
model.compile(loss='binary_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])

In [13]:
data['sentiment'] = data['sentiment'].map({'positive' :1 ,'negative':0})
Y =data['sentiment']
Y.head()

<ipython-input-13-420d556beda9>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['sentiment'] = data['sentiment'].map({'positive' :1 ,'negative':0})


0    1
1    1
2    1
3    0
4    1
Name: sentiment, dtype: int64

In [15]:
model.fit(padded, Y,
            epochs=5, verbose=1)


Epoch 1/5
  3/313 [..............................] - ETA: 7:43 - loss: 0.0070 - accuracy: 1.0000

KeyboardInterrupt: ignored

In [47]:
model.wv.most_similar[boring]

AttributeError: ignored

In [24]:
sentence = ["The boring movie of all time ",
            "I have  seen a worst movie like this",
            "the movie plot is good but it had bad acting"]
# convert to a sequence
sequences = tok.texts_to_sequences(sentence)
# pad the sequence
padded = pad_sequences(sequences, padding='post', maxlen=955)
# Get labels based on probability 1 if p>= 0.5 else 0
prediction = model.predict(padded)

1/1 [==============================] - 0s 184ms/step


In [25]:
prediction

array([[0.8774749 ],
       [0.43636447],
       [0.84576255]], dtype=float32)

In [36]:
words.append(simple_preprocess(sent))

words

[['big',
  'disappoint',
  'think',
  'worst',
  'mastroianni',
  'movi',
  'ever',
  'made',
  'cosmato',
  'tri',
  'hard',
  'make',
  'movi',
  'masterpiec',
  'make',
  'movi',
  'typic',
  'art',
  'movi',
  'give',
  'movi']]

In [37]:
import gensim
#define word2vec
mod = gensim.models.Word2Vec(words,window = 10,min_count =2 ,workers = 4)

In [78]:
#build vocab .
mod.build_vocab(words)

In [36]:
#train word2vec

#mod.train(words,total_examples = mod.corpus_count,epochs = mod.epochs)

(2754787, 3049980)

In [72]:

print(mod.wv['br'])

[-0.20747557  0.65835696  1.5836954   1.8847256  -1.2745984  -1.7183027
  1.7894201   0.7543794  -0.6471495  -0.3201893   0.01383463 -0.6048214
 -0.48625556  1.008865   -0.19947489 -0.76366556 -1.049311    0.9469812
  0.11212298 -0.957521    1.4975128   1.0905609  -0.37349117  0.282557
  0.5105638   0.49578246 -0.8105879   0.10769575 -0.85012764 -1.0421408
 -0.26616332  0.918135    0.7921217   0.03693012  0.30365637  0.58092165
  1.7224749  -0.35102063 -0.15597467 -1.4708961  -0.8739336   0.1168583
 -1.2698418  -1.0166347   0.5050081  -0.28147393 -1.5333359   1.1349472
  0.22123137  0.07500926 -0.55497646 -0.3157701  -0.11551899  0.6886028
  0.20119265 -0.13541189 -0.03415059 -1.1504213  -1.0208195   1.2261822
  1.0636607   0.23133165 -0.5382817  -1.4612048   0.51405543  0.29344314
  0.2092542   1.3992234  -0.8350706   0.70117223 -0.24867398  0.804957
  0.22699963 -1.5047206  -0.0335269   0.79408026  0.02301412  0.27483782
 -0.27736434 -0.1668216  -0.14038262 -0.05015643 -0.3239186   0

In [40]:
mod.wv.similar_by_word('answer')

[('forget', 0.9916181564331055),
 ('whether', 0.9891392588615417),
 ('question', 0.9884751439094543),
 ('anywher', 0.9880257248878479),
 ('pay', 0.9859738349914551),
 ('nobodi', 0.9820170998573303),
 ('fool', 0.9793029427528381),
 ('anybodi', 0.9785446524620056),
 ('ticket', 0.9778914451599121),
 ('ahead', 0.9777400493621826)]

In [41]:
mod.wv.similar_by_word('answer')

[('forget', 0.9916181564331055),
 ('whether', 0.9891392588615417),
 ('question', 0.9884751439094543),
 ('anywher', 0.9880257248878479),
 ('pay', 0.9859738349914551),
 ('nobodi', 0.9820170998573303),
 ('fool', 0.9793029427528381),
 ('anybodi', 0.9785446524620056),
 ('ticket', 0.9778914451599121),
 ('ahead', 0.9777400493621826)]

In [23]:
lst = []
for i in range(0,10000):
  lst.append(len(token[i]))

print(max(lst))

955


In [44]:
#padding
from tensorflow.keras.preprocessing.sequence import pad_sequences

padded = pad_sequences(token,padding='pre',maxlen =939 )

In [46]:
Y = pd.DataFrame(data['sentiment'])

In [45]:
data['sentiment'] = data['sentiment'].map({'positive' :1 ,'negative':0})


<ipython-input-45-83c24be7c037>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['sentiment'] = data['sentiment'].map({'positive' :1 ,'negative':0})


In [12]:
vocab_size = len(tok.word_index)+1
vocab_size

46096

In [55]:
#creating embedding matrix
import numpy as np
embedding_matrix = np.zeros((vocab_size,100))

for word,i in tok.word_index.items():
  if word in mod.wv:
    embedding_matrix[i] = mod.wv[word]


embedding_matrix




array([[ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [-0.20747557,  0.65835696,  1.58369541, ..., -0.37330219,
         0.07516905,  0.81425017],
       [-0.28667495,  0.7854417 ,  0.41262412, ..., -0.33225435,
        -0.65407127, -0.14281018],
       ...,
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ]])

In [73]:
embedding_matrix[0]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [21]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test =train_test_split(X,y,test_size =0.3)


In [1]:
import pandas as pd
import numpy as np
data = pd.read_csv('yelp.csv')
data.head()

business_id        date               review_id  stars  \
0  9yKzy9PApeiPPOUJEtnvkg  2011-01-26  fWKvX83p0-ka4JS3dc6E5A      5   
1  ZRJwVLyzEJq1VAihDhYiow  2011-07-27  IjZ33sJrzXqU-0X6U8NwyA      5   
2  6oRAC4uyJCsJl1X0WZpVSA  2012-06-14  IESLBzqUCLdSzSqm0eCSxQ      4   
3  _1QQZuf4zZOyFCvXc0o6Vg  2010-05-27  G-WvGaISbqqaMHlNnByodA      5   
4  6ozycU1RpktNG2-1BroVtw  2012-01-05  1uJFq2r5QfJG_6ExMRCaGw      5   

                                                text    type  \
0  My wife took me here on my birthday for breakf...  review   
1  I have no idea why some people give bad review...  review   
2  love the gyro plate. Rice is so good and I als...  review   
3  Rosie, Dakota, and I LOVE Chaparral Dog Park!!...  review   
4  General Manager Scott Petello is a good egg!!!...  review   

                  user_id  cool  useful  funny  
0  rLtl8ZkDX5vH5nAx9C3q5Q     2       5      0  
1  0a2KyEL0d3Yb1V6aivbIuQ     0       0      0  
2  0hT2KtfLiobPvh6cDC8JQg     0       1      0  
3  uZetl9T0NcROGOyFfughhg     1       2      0  
4  vYmM4KTsC8ZfQBg-j5MWkw     0       0      0

In [2]:
print(data.info())
print(data.isnull().sum())
data.duplicated().sum()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   business_id  10000 non-null  object
 1   date         10000 non-null  object
 2   review_id    10000 non-null  object
 3   stars        10000 non-null  int64 
 4   text         10000 non-null  object
 5   type         10000 non-null  object
 6   user_id      10000 non-null  object
 7   cool         10000 non-null  int64 
 8   useful       10000 non-null  int64 
 9   funny        10000 non-null  int64 
dtypes: int64(4), object(6)
memory usage: 781.4+ KB
None
business_id    0
date           0
review_id      0
stars          0
text           0
type           0
user_id        0
cool           0
useful         0
funny          0
dtype: int64


0

In [7]:
#text preprocessing
from nltk.stem import PorterStemmer
ps = PorterStemmer()
import re
corpus =[]
for  i in range(len(data['text'])):
  review = re.sub('[^a-zA-Z]',' ',data['text'][i])
  review = review.lower()
  review = review.split()
  review = [ps.stem(words) for words in review if words not in stopwords.words('english')]
  review = ' '.join(review)
  corpus.append(review)


corpus[4]



'gener manag scott petello good egg go detail let assur issu albeit rare speak scott treat guy respect state case surpris walk total satisfi like alway say mistak inevit recov import thank scott awesom staff got custom life'

In [14]:
#stopwords.words('english')
from sklearn.feature_extraction.text import TfidfVectorizer
tf = TfidfVectorizer(max_features =5000,ngram_range=(2,2))
corpus_new = tf.fit_transform(corpus).toarray()

y = data['stars']



In [19]:
X = pd.DataFrame(corpus_new)

In [22]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
mo = lr.fit(x_train,y_train)
y_pred= mo.predict(x_test)
accuracy_score(y_test,y_pred)


/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.44266666666666665

ValueError: ignored

In [23]:
##naive bayes
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score
mn = MultinomialNB()
model = mn.fit(x_train,y_train)
pred = model.predict(x_test)
accuracy_score(y_test,pred)

0.43233333333333335

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=3000)
dat = cv.fit_transform(corpus)

In [ ]:
dat.shape

(5000, 3000)

In [ ]:
#word to vec conversion
#one-hot , bow,tf-idf or tokenize and get numeric data
# in one hot we define voc_size .
voc_size = 10000
from tensorflow.keras.preprocessing.text import one_hot
one_hotrep = [one_hot(words,voc_size) for words in corpus ]
one_hotrep

[[3505,
  1101,
  7647,
  4015,
  2835,
  4662,
  5951,
  5815,
  6362,
  8315,
  2359,
  2359,
  2373,
  751,
  8181,
  2835,
  7174,
  3367,
  9511,
  4902,
  1394,
  5815,
  490,
  1465,
  7792,
  8465,
  7183,
  1413,
  7530,
  8465,
  7142,
  2556,
  240,
  229,
  9802,
  4902,
  9315,
  7784,
  4271,
  490,
  2359,
  2359,
  4954,
  2835,
  44,
  5682,
  8152,
  7873,
  7235,
  4282,
  467,
  7994,
  1468,
  5169,
  5504,
  2987,
  8068,
  6140,
  4627,
  2225,
  2198,
  8696,
  4662,
  1113,
  5327,
  6109,
  1440,
  5504,
  1576,
  1621,
  7647,
  7564,
  3394,
  6369,
  1460,
  9825,
  5254,
  1356,
  4742,
  5374,
  803,
  6611,
  7538,
  3043,
  468,
  8727,
  138,
  2359,
  2359,
  6212,
  5067,
  2796,
  5174,
  8465,
  8106,
  5585,
  3897,
  8465,
  3674,
  9271,
  3252,
  7607,
  4038,
  8358,
  2846,
  9271,
  1212,
  9271,
  7363,
  2835,
  7076,
  4099,
  2373,
  4662,
  1585,
  2784,
  8181,
  7478,
  9347,
  5067,
  7717,
  4015,
  7722,
  7402,
  2835,
  4109,
  8

In [ ]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM,Dense

In [68]:
token[2]

[105,
 106,
 29,
 688,
 6,
 740,
 1205,
 1918,
 431,
 631,
 1452,
 574,
 10,
 364,
 316,
 107,
 41,
 4224,
 328,
 1738,
 12,
 1425,
 14,
 17,
 4225,
 934,
 997,
 336,
 122,
 281,
 428,
 696,
 86,
 1798,
 1426,
 105,
 2523,
 2046,
 1635,
 60,
 1173,
 846,
 333,
 49,
 92,
 2184,
 30,
 1,
 1,
 130,
 4,
 2046,
 107,
 51,
 1569,
 38,
 1242,
 43,
 369,
 12609,
 6715,
 395,
 1102,
 1012,
 648,
 874,
 117,
 735,
 812,
 109,
 164,
 1,
 1,
 122,
 4043,
 4226,
 530,
 16223,
 1551,
 900,
 12610,
 71,
 1883,
 27,
 107,
 22,
 11,
 136]

In [76]:
#padding
# two tpye -post ,pre
#padding - appendign zeros to vectors to match with longest sent. and maintian uniformity
from tensorflow.keras.preprocessing.sequence import pad_sequences
emb = pad_sequences(x_train,padding ='pre',maxlen =400 )

array([[   0,    0,    0, ..., 9396, 2264,  459],
       [   0,    0,    0, ..., 4992, 3866, 6324],
       [   0,    0,    0, ..., 4535, 5356, 9342],
       ...,
       [   0,    0,    0, ..., 5568,  287, 5766],
       [   0,    0,    0, ..., 9358,  220, 1051],
       [   0,    0,    0, ..., 9721, 8477, 9721]], dtype=int32)

In [61]:
from keras.layers import Dense, Embedding, Bidirectional, LSTM,Dropout
from keras.models import Sequential
from keras.preprocessing.text import Tokenizer


In [62]:
#TOT_SIZE = len(tokenizer.word_index)+1

lstm_model = Sequential()
lstm_model.add(Embedding(vocab_size, 100, weights = [embedding_matrix] ,input_length=100))
lstm_model.add(Bidirectional(LSTM(100)))
lstm_model.add(Dropout(0.4))
lstm_model.add(Dense(20, activation="relu"))
lstm_model.add(Dropout(0.3))
lstm_model.add(Dense(1, activation = "sigmoid"))

In [74]:
lstm_model.compile(loss = "binary_crossentropy", optimizer = "adam", metrics = ["accuracy"])
lstm_model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 100, 100)          2610100   
                                                                 
 bidirectional (Bidirectiona  (None, 200)              160800    
 l)                                                              
                                                                 
 dropout (Dropout)           (None, 200)               0         
                                                                 
 dense (Dense)               (None, 20)                4020      
                                                                 
 dropout_1 (Dropout)         (None, 20)                0         
                                                                 
 dense_1 (Dense)             (None, 1)                 21        
                                                      

In [75]:
lstm_model.fit(x_train,Y,epochs = 5, validation_split=0.3, batch_size=16)

ValueError: ignored

In [ ]:
#

from keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer() #initializing the tokenizer
tokenizer.fit_on_texts(corpus)# fitting on the sms data
text_to_sequence = tokenizer.texts_to_sequences(corpus)

In [ ]:
tokenizer.index_word[26000]

'constrain'

In [ ]:
tokenizer.index_word[12000]

'mcavoy'

In [ ]:
df = pd.DataFrame(data.iloc[:,3])
df.tail()
data.shape

(18285, 5)

In [ ]:
Y = data.iloc[:,5]
Y.head()

0    1
1    0
2    1
3    1
4    1
Name: label, dtype: int64

In [ ]:
Y = pd.DataFrame(Y)
Y.head()

label
0      1
1      0
2      1
3      1
4      1

In [ ]:
y= Y.iloc[0:2000]

In [ ]:
from nltk.stem import PorterStemmer
ste =  PorterStemmer()
import re
corpus = []
for i in range(len(dat['review'])):
  text = re.sub('[^a-zA-Z]',' ',dat['review'][i])
  text = text.lower()
  text = nltk.word_tokenize(text)
  text = [ste.stem(word) for word in text if word not in set(stopwords.words('english')) ]
  text = ' '.join(text)
  corpus.append(text)


corpus[3]


'basic famili littl boy jake think zombi closet parent fight time br br movi slower soap opera suddenli jake decid becom rambo kill zombi br br ok first go make film must decid thriller drama drama movi watchabl parent divorc argu like real life jake closet total ruin film expect see boogeyman similar movi instead watch drama meaningless thriller spot br br well play parent descent dialog shot jake ignor'

In [ ]:
len(corpus)

5572

In [ ]:
vocab_size = 5000
onehot = [one_hot(words,vocab_size ) for words in corpus]
onehot[3]

[300, 4421, 2314, 4486, 3605, 585, 4291]

In [ ]:
onehot[3]

[2927, 4589, 1294, 4609, 2151, 2927, 3587, 4014, 1294]

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 6000)
wor = cv.fit_transform(corpus).toarray()

len(wor[1])

6000

In [ ]:
#one hot -embedding layer
#-tokenize - embedding layer
#word2vec-tokenize -embedding layer or word2vec -tokenize -ML algo

In [ ]:
import numpy as np
lst = []
lst.append(wor[3])



AttributeError: ignored

In [ ]:
def find_indices(l, value):
    return [
        index for index, item in enumerate(l)
        if item == value
    ]

print(find_indices(lst,1))

ValueError: ignored

In [ ]:
text = re.sub('[^a-zA-Z]',' ',data['labels'][2])
text = text.lower()
text = text.split()

'a'

In [ ]:
from tensorflow.keras.preprocessing.text import one_hot

In [ ]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [ ]:
vocab_size = 5000

In [ ]:
onehot = [one_hot(word,vocab_size) for word in corpus]


In [ ]:
onehot[3]

[4772, 2103, 1436, 4171, 4706, 4772, 1236, 2557, 1436]

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
tiv = TfidfVectorizer(ngram_range = (1,3))

x = tiv.fit_transform(corpus).toarray()

In [ ]:
X = pd.DataFrame(x)

NameError: ignored

In [ ]:
from sklearn.model_selection import train_test_split
x_train , x_test, y_train,y_test =  train_test_split(X,y,test_size = 0.2)


NameError: ignored

In [ ]:
#word2vec - one hot rep - CBOW,Skipgrams .
from sklearn.naive_bayes import MultinomialNB
nb = MultinomialNB()
model = nb.fit(x)

In [ ]:
import pandas as pd
data = pd.read_csv('SMSSpamCollection.csv',sep ='\t',names = ['text','label'])  # Replace with your dataset
texts = data['text']
labels = data['label'].map({'ham': 0, 'spam': 1})
data.head()

text                                              label
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [ ]:
import numpy as np
import pandas as pd
from gensim.models import Word2Vec
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import to_categorical

# Load SMS spam dataset (replace with your dataset)
data = pd.read_csv('SMSSpamCollection.csv',sep ='\t',names = ['label','text'])  # Replace with your dataset
texts = data['text']
labels = data['label'].map({'ham': 0, 'spam': 1})

# Split the dataset
X_train, X_test, y_train, y_test = train_test_split(texts, labels, test_size=0.2, random_state=42)

# Tokenize and create vocabulary




# Pad sequences to have the same length


# Load or train Word2Vec model (replace with your code)
word2vec_model = Word2Vec(sentences=[text.split() for text in X_train], vector_size=100, window=5, min_count=1, sg=1)

# Function to convert texts to Word2Vec embeddings
def embed_text(text):
    embeddings = []
    for word in text.split():
        if word in word2vec_model.wv:
            embeddings.append(word2vec_model.wv[word])
    return np.array(embeddings)

# Convert text sequences to Word2Vec embeddings
X_train_embedded = pd.DataFrame([embed_text(text) for text in X_train])
X_test_embedded = pd.DataFrame([embed_text(text) for text in X_test])

# Build a simple feedforward neural network



# Build a simple feedforward neural network
model = Sequential([
    Flatten(input_shape=(100, word2vec_model.vector_size)),
    Dense(128, activation='relu'),
    Dense(1, activation='sigmoid')
])

# Compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Train the model
model.fit(X_train_embedded, y_train, epochs=10, batch_size=32, validation_split=0.2)

# Evaluate the model
loss, accuracy = model.evaluate(X_test_embedded, y_test)
print(f"Test Loss: {loss:.4f}, Test Accuracy: {accuracy:.4f}")

/usr/local/lib/python3.10/dist-packages/pandas/core/internals/construction.py:568: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  values = np.array([convert(v) for v in values])


ValueError: ignored

In [ ]:
import numpy as np
import pandas as pd
from gensim.models import Word2Vec
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import to_categorical

# Load SMS spam dataset (replace with your dataset)
data = pd.read_csv('SMSSpamCollection.csv',sep ='\t',names = ['label','text'])  # Replace with your dataset
texts = data['text']
labels = data['label'].map({'ham': 0, 'spam': 1})

# Split the dataset
X_train, X_test, y_train, y_test = train_test_split(texts, labels, test_size=0.2, random_state=42)

# Tokenize and create vocabulary
tokenizer = Tokenizer()
tokenizer.fit_on_texts(X_train)
vocab_size = len(tokenizer.word_index) + 1

# Convert text to sequences
X_train_sequences = tokenizer.texts_to_sequences(X_train)
X_test_sequences = tokenizer.texts_to_sequences(X_test)

# Pad sequences to have the same length
max_sequence_length = 100  # You can adjust this based on your dataset and requirements
X_train_padded = pad_sequences(X_train_sequences, maxlen=max_sequence_length, padding='post')
X_test_padded = pad_sequences(X_test_sequences, maxlen=max_sequence_length, padding='post')

# Load or train Word2Vec model (replace with your code)
word2vec_model = Word2Vec(sentences=[text.split() for text in X_train], vector_size=100, window=5, min_count=1, sg=1)

# Function to convert texts to Word2Vec embeddings
def embed_text(text):
    embeddings = []
    for word in text.split():
        if word in word2vec_model.wv:
            embeddings.append(word2vec_model.wv[word])
    return np.array(embeddings)

# Convert text sequences to Word2Vec embeddings
X_train_embedded =  pd.DataFrame([embed_text(text) for text in X_train])
X_test_embedded =  pd.DataFrame([embed_text(text) for text in X_test])


# Build a simple feedforward neural network
model = Sequential([
    Flatten(input_shape=(max_sequence_length, word2vec_model.vector_size)),
    Dense(128, activation='relu'),
    Dense(1, activation='sigmoid')
])

# Compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Train the model
model.fit(X_train_embedded, y_train, epochs=10, batch_size=32, validation_split=0.2)

# Evaluate the model
loss, accuracy = model.evaluate(X_test_embedded, y_test)
print(f"Test Loss: {loss:.4f}, Test Accuracy: {accuracy:.4f}")


/usr/local/lib/python3.10/dist-packages/pandas/core/internals/construction.py:568: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  values = np.array([convert(v) for v in values])


ValueError: ignored